### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ndq880815** [dmikusa-pivotal/cf-ex-code-igniter#1]
Browser got a response with 400 Bad Request (See image below) though everything was fine with deployment to Bluemix.

![image](https://cloud.githubusercontent.com/assets/2411073/5704386/297d1c46-9a71-11e4-8fc6-db9142187d9d.png)

Is there any solution for that?

**Comment by dmikusa** [comment]
Example was out of date.  I've updated it.  Should be working now.  Give it a try.

**Comment by ndq880815** [comment]
Yes, it works now. Thanks for fixing.
Additionally, database connection seems still has problem. After clicking "view news" or "create news", just got a blank page. I met this kind of problem in phpMyAdmin too, but when it was changed to "cf-ex-phpmyadmin" which is also your repository, it just worked fine. Any idea about that?

**Comment by dmikusa** [comment]
If you follow [the steps here](https://github.com/dmikusa-pivotal/cf-ex-code-igniter#usage) it should work fine.  It's likely failing because you didn't bind the service (you may need to change the service name in manifest.yml) or create the database table (not done automatically in this example, although you could automate this in your code).

Dan

**Comment by ndq880815** [comment]
I have had bound the service and certainly modified the manifest.yml. The only difference is that the service is 'mysql' instead of 'clearDB-mysql'. Environment variables are available. Because the service works fine with phpMyAdmin , that's why I guess there is something wrong in CI.

![image](https://cloud.githubusercontent.com/assets/2411073/5722096/8853e650-9b39-11e4-9c8d-6f72e0dead98.png)

**Comment by dmikusa** [comment]
I think I understand what you mean.  If the MySQL instance you're using is not ClearDb, you'll probably need to [edit this part of the code](https://github.com/dmikusa-pivotal/cf-ex-code-igniter/blob/master/application/config/database.php#L49-L50).

Currently it's setup to look for the service provider "cleardb" and take the first bound instance of that provider.  The easiest solution if you have a different provider name, which it sounds like you do, is to  change line #50.  You can find your provider name by running `cf env <app>` and looking at VCAP_SERVICES.

The reason that the PHPMyAdmin example works is because PHPMyAdmin supports accessing multiple MySQL servers, so its example will loop through all of the bound MySQL service instances and configure the app to use all of them.  In short, the way it configures the MySQL connections is more robust.

This example is less flexible about how it searches for the bound MySQL instance to use.  You could certainly change the code so that it's more robust like the [PHPMyAdmin example](https://github.com/dmikusa-pivotal/cf-ex-phpmyadmin/blob/master/htdocs/config.inc.php#L27-L48), but that's a little more involved.

Dan

**Comment by ndq880815** [comment]
That's actually right. I realized and updated it according to  PHPMyAdmin example,  but still not work. However, finally I found what's wrong. "options.json" was missing under .bp/config. Based on these two points I made a pull request.
Thanks a lot anyway.
